<?php
/**
 * @file
 * Code for the apex_pages feature.
 */

include_once 'apex_pages.features.inc';

/**
 * Implements hook_menu_block_blocks().
 */
function related_links_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'related links-1' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Related Sections Menu',
      'level'       => 2,
      'follow'      => 0,
      'depth'       => 0,
      'expanded'    => 0,
      'sort'        => 0,
    ),
  );
}
